config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  concern :commented do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true do
      patch :mark_as_best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  concern :commented do
    resources :comments, shallow: true, only: :create
  end

  resources :links, only: :destroy
  resources :attachments, only: :destroy
  resources :rewards, only: :index
  resources :searches, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities

    can :me, User, user_id: user.id
    can :index, User, user_id: user.id

    can :create, [Question, Answer, Comment, Subscription]
    can :update, [Question, Answer], user_id: user.id
    can :destroy, [Question, Answer, Subscription], user_id: user.id

    can :destroy, ActiveStorage::Attachment do |file|
      user.author_of?(file.record)
    end

    can :destroy, Link, linkable: { user_id: user.id }

    can :mark_as_best, Answer, question: { user_id: user.id }

    can %i[vote_up vote_down cancel_vote], [Answer, Question] do |votable|
      !user.author_of?(votable)
    end
  end
end

# See the wiki for details:
# https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  validates :body, presence: true
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  after_create :email_notification

  default_scope { order(best: :desc).order(created_at: :asc) }

  def mark_best!
    transaction do
      self.class.where(question_id: question_id).update(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def email_notification
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, touch: true

  validates :body, presence: true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true, touch: true
  validates :name, :url, presence: true
  validates :url, http_url: true

  def gist?
    URI(url).scheme == 'https' && URI(url).host == 'gist.github.com'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy

  has_one :reward, dependent: :destroy
  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  after_create :calculate_reputation, :subscribe_to_author!

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_to_author!
    subscriptions.create!(user: user)
  end
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :question

  has_one_attached :image

  validates :title, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates_presence_of :question
  validates_presence_of :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
          :registerable, :recoverable, 
          :rememberable, :validatable, 
          :confirmable,  :omniauthable, 
          omniauth_providers: [:github]


  def author_of?(item)
    id == item.user_id
  end

  def self.find_for_oauth(auth)
    FindForOauthService.new(auth).call
  end

  def subscribed_of?(question)
    question.subscriptions.find_by(user_id: id).present?
  end

  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid)
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user

  validates :value, presence: true
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_question, only: %i[create]
  before_action :find_answer, only: %i[destroy update mark_as_best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    authorize! :update, @answer
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    authorize! :destroy, @answer
    @answer.destroy if current_user.author_of?(@answer)
  end

  def mark_as_best
    @answer.mark_best! if current_user.author_of?(@answer.question)
  end

  private

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast("question_#{@question.id}_answers", answer: @answer)
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  before_action :authenticate_user!, only: %i[destroy]
  before_action :find_link

  skip_authorization_check

  def destroy
    @link.destroy if current_user&.author_of?(@link.linkable)
  end

  private

  def find_link
    @link = Link.find(params[:id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
  def show_best?(answer)
    current_user&.author_of?(answer.question) && !answer.best?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_update_at = klass.maximum(:update_at).try(:utc).try(:to_s, number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_update_at}"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/helpers/rewards_helper.rb
# frozen_string_literal: true

module RewardsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= Gon::Base.render_data %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p class="search"><%= render "searches/form" %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_add_links.html.slim
p Links:
#links
  = f.fields_for :links do |l|
    = render 'shared/link_fields', f: l
  .add_links
  = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

app/views/shared/_attachments.html.slim
- if resource.files.attached?
  .attachments
    - resource.files.each do |file|
      div id="attachment_#{file.id}"
        = link_to file.filename.to_s, url_for(file)
        - if current_user&.author_of?(resource)
          p= button_to 'Delete file', attachment_path(file), method: :delete, remote: true

app/views/shared/_comments.html.slim
-cache commentable do
  h4 Comments
  .comments id="#{commentable.class.name.underscore}_#{commentable.id}_comments" data-commentable="#{commentable.class.name.underscore}" data-commentable-id="#{commentable.id}"

    = render commentable.comments
- if current_user
  = link_to 'Add comment', '#', class: 'add-comment', id: "add-comment-#{commentable.class.name.underscore}-#{commentable.id}", data: { commentable: "#{commentable.class.name.underscore}-#{commentable.id}" }

  = form_with model: [commentable, Comment.new], class: 'comment-form hidden', id: "comment-form-#{commentable.class.name.underscore}-#{commentable.id}", local: false do |f|
    .comment-errors = render 'shared/errors', resource: @comment
    .field.form-group
      = f.label :body, 'Comment body'
      = f.text_area :body, class: 'form-control'
    = f.submit "Save comment"

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_errors_html.slim
-if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_link_fields.html.slim
.nested-fields
  p
    =f.label :name, 'Link name'
    =f.text_field :name
  p
    =f.label :url
    =f.text_field :url
  = link_to_remove_association "remove link", f

app/views/shared/_links.html.slim
- resource.links.each do |link|
  - if link.persisted?
    div id="link_#{link.id}"
      - if link.gist?
        = link.name
        script src="#{link.url}.js"
      -else
        li= link_to link.name, link.url

      - if current_user&.author_of?(resource)
        p= link_to 'Delete link', link_path(link), method: :delete, remote: true

app/views/shared/_vote.html.slim
-if current_user && !current_user.author_of?(resource)
  .vote
    p
      = link_to 'Like', polymorphic_path(resource, action: :vote_up),
              method: :patch,
              data: { type: :json },
              remote: true

    p.rating
      = resource.rating
    p
      = link_to "Don't like", polymorphic_path(resource, action: :vote_down),
              method: :patch,
              data: { type: :json },
              remote: true

      p
        = link_to 'Cancel vote', polymorphic_path(resource, action: :cancel_vote),
                method: :delete,
                data: { type: :json },
                remote: true