config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  concern :commented do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true do
      patch :mark_as_best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  concern :commented do
    resources :comments, shallow: true, only: :create
  end

  resources :links, only: :destroy
  resources :attachments, only: :destroy
  resources :rewards, only: :index
  resources :searches, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  validates :body, presence: true
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  after_create :email_notification

  default_scope { order(best: :desc).order(created_at: :asc) }

  def mark_best!
    transaction do
      self.class.where(question_id: question_id).update(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def email_notification
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_question, only: %i[create]
  before_action :find_answer, only: %i[destroy update mark_as_best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    authorize! :update, @answer
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    authorize! :destroy, @answer
    @answer.destroy if current_user.author_of?(@answer)
  end

  def mark_as_best
    @answer.mark_best! if current_user.author_of?(@answer.question)
  end

  private

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast("question_#{@question.id}_answers", answer: @answer)
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  skip_authorization_check

  before_action :find_question, only: %i[index create]
  before_action :find_answer, only: %i[show update destroy]

  def index
    authorize! :index, Answer
    render json: @question.answers
  end

  def show
    authorize! :show, Answer
    render json: @answer, serializer: AnswerOneSerializer
  end

  def create
    authorize! :create, Answer
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, Answer

    if @answer.update(answer_params)
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @answer

    @answer.destroy
    render json: { messages: ["Answer was successfully deleted."] }
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
  def show_best?(answer)
    current_user&.author_of?(answer.question) && !answer.best?
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  - cache answer do
    .answer id = "answer-#{answer.id}"
      - if answer.best?
        b= "Best answer:"

      p= answer.body

      = render 'shared/vote', resource: answer

      .answer-comments
        = render 'shared/comments', commentable: answer
      hr

      .links
        p Links:
        ul
          = render 'shared/links', resource: answer


      = render 'shared/attachments', resource: answer

      - if show_best?(answer)
        p= link_to 'Mark as best', mark_as_best_answer_path(answer),
                remote: true,
                method: :patch

      - if current_user&.author_of?(answer)
        p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        p= button_to 'Delete answer', answer_path(answer),
                remote: true,
                method: :delete

      = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false do |f|
        p
          = f.label :body, 'Your answer'
          = f.text_area :body
        p
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
        p
          #links
            = f.fields_for :links do |l|
            .add_link
              = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
        p
          = f.submit 'Save'

  hr

app/views/answers/_form.html.slim
.answer-errors
  =render 'shared/errors', resource: @answer

= form_with model: [@question, @answer], class: 'new-answer', local: false do |f|
  p
    = f.label :body, 'Your answer'
    = f.text_area :body
  p
    =f.label  :files
    =f.file_field :files, multiple: true, direct_upload: true
  p
    = render 'shared/add_links', f: f
  p
    = f.submit 'New answer'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
  location.reload();

<% end %>

app/views/answers/destroy.js.erb
$("#answer-<%= @answer.id %>").remove();

app/views/answers/mark_as_best.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
$('.answers').html("<%= j render @answer.question.answers %>");
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% unless @answer.errors.present? %>
  $('.answers' ).html('<%= j render @question.answers %>');
<% end %>