config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
      delete :cancel_vote
    end
  end

  concern :commented do
    resources :comments, shallow: true, only: :create
  end

  resources :questions, concerns: %i[voted commented] do
    resources :answers, concerns: %i[voted commented], shallow: true do
      patch :mark_as_best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  concern :commented do
    resources :comments, shallow: true, only: :create
  end

  resources :links, only: :destroy
  resources :attachments, only: :destroy
  resources :rewards, only: :index
  resources :searches, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_authorization_check

  def index
    @results = SearchService.call(query_params)
  end

  private

  def query_params
    params.permit(:query, :scope, :commit)
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_answer.html.slim
p = resource.body

app/views/searches/_comment.html.slim
p = resource.body

app/views/searches/_form.html.erb
<%= form_with url: searches_path, method: :get, local: true do |f| %>
  <%= f.label :query %>
  <%= f.text_area :query %>
  <%= f.label :scope %>
    <%= f.select :scope, options_for_select([%w(All thinking_sphinx),
      %w(Question question),
      %w(Answer answer),
      %w(Comment comment),
      %w(User user)]) %>
    <%= f.submit 'Search' %>
  <% end %>

app/views/searches/_question.html.slim
p = resource.title
p = resource.body

app/views/searches/_user.html.slim
p = resource.email

app/views/searches/index.html.slim
h1 Search results:
-if !@results.empty?
  - @results.each do |result|
    = render partial: result.class.to_s.downcase, locals: { resource: result }
-else
  h2 Nothing found
p= link_to 'Back to Questions', questions_path